import { Link } from 'react-router-dom';
import { GraduationCap, ArrowRight, BookOpen, Users, Building2, ShieldCheck, CheckCircle2, Phone, Mail, MapPin } from 'lucide-react';

export default function PublicHome(){
 const facilities=['Smart classrooms','Science & computer labs','Library & reading room','Sports facilities','Safe campus','Student support'];
 return <div className="public-site"><header className="public-nav"><div className="public-brand"><div className="brand-icon"><GraduationCap size={22}/></div><b>Bright Future School</b></div><nav><a href="#about">About</a><a href="#academics">Academics</a><a href="#facilities">Facilities</a><a href="#contact">Contact</a><Link className="nav-login" to="/login">Staff Login</Link></nav></header>
 <section className="hero"><div className="hero-content"><span className="eyebrow">Excellence • Character • Future</span><h1>Learning today.<br/><span>Leading tomorrow.</span></h1><p>A modern school management experience for students, families and staff — built around organized learning and transparent fee management.</p><div className="hero-actions"><a href="#about" className="primary-btn">Explore our school <ArrowRight size={18}/></a><Link to="/login" className="secondary-btn">Staff portal</Link></div></div><div className="hero-panel"><div className="panel-top"><ShieldCheck/><span>Trusted learning environment</span></div><div className="panel-stat"><b>10</b><span>Classes</span></div><div className="panel-stat"><b>50+</b><span>Students</span></div><div className="panel-stat"><b>24/7</b><span>Student focus</span></div></div></section>
 <section id="about" className="section"><div className="section-heading"><span>ABOUT US</span><h2>Building strong foundations for every learner.</h2></div><div className="about-grid"><p>Bright Future School is committed to creating a supportive, disciplined and technology-enabled learning environment. Our focus is on academic growth, confidence, values and practical skills.</p><div className="feature-card"><Users/><h3>Student first</h3><p>Every student receives a safe and supportive environment to learn and grow.</p></div><div className="feature-card"><BookOpen/><h3>Strong academics</h3><p>Structured classes and engaging learning resources for Classes 1–10.</p></div></div></section>
 <section id="academics" className="section soft"><div className="section-heading center"><span>ACADEMICS</span><h2>Classes 1 to 10</h2><p>Clear academic structure with a balanced school experience.</p></div><div className="class-grid">{Array.from({length:10},(_,i)=><div className="class-card" key={i}><div>{i+1}</div><b>Class {i+1}</b><span>Primary & Secondary</span></div>)}</div></section>
 <section id="facilities" className="section"><div className="section-heading center"><span>FACILITIES</span><h2>A campus designed for learning.</h2></div><div className="facility-grid">{facilities.map(x=><div className="facility" key={x}><CheckCircle2 size={19}/><b>{x}</b></div>)}</div></section>
 <section id="contact" className="contact-section"><div><span>CONTACT</span><h2>We'd love to hear from you.</h2><p>Visit our campus or contact the school office for admissions and general enquiries.</p></div><div className="contact-list"><div><Phone size={19}/><span>+91 98765 43210</span></div><div><Mail size={19}/><span>info@brightfutureschool.com</span></div><div><MapPin size={19}/><span>Lucknow, Uttar Pradesh</span></div></div></section>
 <footer><div><b>Bright Future School</b><p>Empowering students through education, values and opportunity.</p></div><div><small>© 2026 Bright Future School. All rights reserved.</small></div></footer></div>
}
